@BASEURL = http://localhost:3030
@contentType = application/json


### GET Welcome
GET {{BASEURL}}

### GET Todos
GET {{BASEURL}}/todos

### Create Todo
POST {{BASEURL}}/todo
Content-Type: {{contentType}}

{
    "todo": "New todo item1",
    "isCompleted": true
}


### DELETE Todo
DELETE {{BASEURL}}/todo/eBPNbH6TOc40qu6DWcRv
Content-Type: {{contentType}}
